version: '1.0.0'
services:
  env:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "chmod 777 /app/start.sh ; /app/start.sh"
    ports:
      - "8022:22"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    
    