version: '1.0.0'
services:
  env:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/bash", "-c", "/home/start.sh && /bin/bash"]
    ports:
      - "8022:22"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    
    